language: elixir
cache:
  directories:
    - deps
    - _build
services:
  - docker
  - postgresql
addons:
  postgresql: "9.6"
  apt:
    packages:
      - postgresql-9.6-postgis-2.3
      - docker-ce
elixir:
  - 1.7.4
otp_release:
  - 21.2.5
notifications:
  slack:
    rooms:
      - secure: "WilReWpOLJvNyW9mASNQ4i2XmGoq6KnD8HX/kHIJg8EuVBrfCVgQ24bDq/L4nMTG3ho911HuGT07Aq1jPuFPT47zMoGGeEn9qAi7Lb/fWIv4XAoig8egCkWBSQkn4z1Yf6rz7HLYyaXRZwFdrkxT65nTO+TN5q3zAnN3UT8RSGG+O0DiWfqULAJkQWi8SHIvYF7L0YOgLphsNo+9qPLhQS+IVlOefcwprWNsAEyyjHfGfzC5UPRjrkuvyqWToSGMu7czKaaUgXJ8Tr5ERZkX6YMF4fe+H5EdbUEWyIaRw+p/0GIIEWAxkO/13ssJ71pISCiqp2Gal3nkjwu4ozOzYqTDtxAXd8PY30J3UK4rdyW9rhAozu/1MyIbnBDh8R1zKfI0SwHhNZjFTd4OH2xR37ly88j5YQlDp4DcTM/GIW0CPCmQ+t2e5moXdd6x4zrg6gBW4qUEwvnPoytA9N8DL4No7ZxF/IMgF+9jg9VipQkB8z/BmkB1IxjpA7049muiQOlGaO43As5zVdYcjBhrGhagxzwba3MWb4uDjgKl92F6IofNlqdMQdd4ZDGArI0lOlnozvCzMHi/oe7JLGdWKvzfDFcF6nBLQZruW16gwQluYmB8LPAK40ft3vLdPPqV8WqcoKLPYCEnAwc/Jcjqqq63jxj50gEZLjanicqv1Bs="
    on_success: always
env:
  global:
    - MIX_ENV=test
    - DOCKER_NAMESPACE=edenlabllc
    - APPS='[{"app":"report_api","chart":"reports","namespace":"reports","deployment":"api","label":"api"}]'
    - POSTGRES_VERSION=9.6
    - secure: "P3zPrTcFnNJv/S6fEwg0rSywqPFU1+k6tORdSYjR932frlYAHhEVausKeqMAd8ny55hmWJT8BHBdWELwoz3el5EaDP+o/A29cV3aSPP4ng2RHo19QWnz2ha8al2f/orfDtZwlV0sFuUJzZAEPgXjgMlbICrRIwQWQEIwXNxVpCajPhCVlysnMUUhlOrQK4HrNqU+TGoCIyU6jXlYGep84BAD+23LgYc5e65Jbx3xIMr61Kd81OS+mbHmnrw0cptcRqvH94xd/p8Z+J6XsUksqvQMeo+HNoIh8l1qUWSnrVvPFLXHevrYqwKPlAKlmlGn7lDJcq9c8oJ6OcGxkrilSsldUvqFgytUpQtCCS8Y6ys2a6oEvwQj9KUWqw49oBTPnHFtC/+CVy94ovaMTY9c0nD4n7OYn7uElJOJGuGebX0ilLVIyQOZn6I9M330AuMh0WDR09UZK1ktnYZOs7teyYJXZ22qoNQZmZqHqUMMw6u2mz8oRsrLvuXXhQWNvstH2iveMM365SAk4vIv5EngEMm+pWpi4FGs1QYj8utRGfo6bWN4Jx1pJwnGji1kbCCYqThH4CZpMs/J3NneWfGbAf6lOoD8tzDZrUAKGI81ea4KlwYIjGNltTQe6LhjUud3hUcuhZp7E1F97Fi2xvodfjZ+QnsxRUzf+hZXVwhD0GI="
    # GitHub Token
    - secure: "BOn8bjRXn+pMIsOni605x/mMGlQukRjc94BB4HIwDoaJ9obJfFdRiTHZwAzG51hnz84BUOvlL2nPCaCh3CCBeH/smdaRb6DdhzWiV6nD3f5soh9FkCvGIn2rUKwcmJZbT5NlclQZexW/O2ESE+X1llGQIOl18/4iXGUcVcG6t80uuLYpac18S0LDycA3rh3rmcqHEG/NnQf4aaG+Q4BMunBrkr59fSDaqJqQbrkKDb9VkxJ7+CFvWwbO3SIYBkexjTFccfAKCVSgglARpqR3V93QDUSAtyfPbnt3grUe2VCuoN6m4+KIaQeHMQTa41fKuRFL8BZpRJxqw3oU5Sy4LiKGSC5JrbtOoz3MFilEqbOsls2B1LIPYsGOs6bn/DQeg4maxaGZtRCQmkWYFU10phfNcCb6Qn3gKTHUALb6GIm8P/ahDxM28USDVlG77d6+WwHU8wVC/hffbPFUTztvo8KpRA4A9aSEDvito+DJySVo74f+1aKsluK7IYDe/8y+Pzw8geTgpM1tgr3JNsxcA6norlDPFnZHXHQjoIC9ZaCqxOxUq4vp04FxgIRhccMi+Fp+ChLUIvnzq3IsCqrwgc+aVXlfXrfibn4hAvfz1Z4vFTtOaAMjQHba/XDFG7BOZCXsfdSzUmCJTEt1HeTKkEVqGMAgLUAfgQbKtTvLDrk="
branches:
  # Releases are generated automatically, stop infinite build loop
  except:
    - /^[0-9]*\.[0-9]*\.[0-9]*/
before_install:
  - sudo apt-get install jq
  - curl -s https://raw.githubusercontent.com/edenlabllc/ci-utils/umbrella/init-db.sh -o init-db.sh; sudo sh ./init-db.sh
jobs:
  include:
    - stage: "test and build"
      # run tests
      script: (curl -s https://raw.githubusercontent.com/edenlabllc/ci-utils/umbrella_v2/tests.sh -o tests.sh; bash ./tests.sh) || travis_terminate 1
      # Build Docker container
    - stage: "test and build"
      env: APPS='[{"app":"report_api","chart":"reports","namespace":"reports","deployment":"api","label":"api"}]'
      # "Decrypting deploy key..."
      script:
      - openssl aes-256-cbc -K $encrypted_7e692fa65543_key -iv $encrypted_7e692fa65543_iv -in eHealth-8110bd102a69.json.enc -out eHealth-8110bd102a69.json -d
      - (curl -s https://raw.githubusercontent.com/edenlabllc/ci-utils/umbrella_v2/docker.sh -o docker.sh; bash ./docker.sh) || travis_terminate 1
    - stage: "test and build"
      env: APPS='[{"app":"capitation","chart":"reports","namespace":"reports","job":"true"}]'
      # "Decrypting deploy key..."
      script:
      - openssl aes-256-cbc -K $encrypted_7e692fa65543_key -iv $encrypted_7e692fa65543_iv -in eHealth-8110bd102a69.json.enc -out eHealth-8110bd102a69.json -d
      - (curl -s https://raw.githubusercontent.com/edenlabllc/ci-utils/umbrella_v2/docker.sh -o docker.sh; bash ./docker.sh) || travis_terminate 1
    - stage: "test and build"
      env: APPS='[{"app":"report_cache","chart":"reports","namespace":"reports","deployment":"cache","label":"cache"}]'
      # "Decrypting deploy key..."
      script:
      - openssl aes-256-cbc -K $encrypted_7e692fa65543_key -iv $encrypted_7e692fa65543_iv -in eHealth-8110bd102a69.json.enc -out eHealth-8110bd102a69.json -d
      - (curl -s https://raw.githubusercontent.com/edenlabllc/ci-utils/umbrella_v2/docker.sh -o docker.sh; bash ./docker.sh) || travis_terminate 1
